version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql-lar01
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootsecret
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 5

    app:
        build:
            context: .
        container_name: app-lar01
        ports:
            - "8000:80"
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - ./:/var/www/html
            - node_modules:/var/www/html/node_modules
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: secret

volumes:
    mysql-data:
    node_modules:
